---
- name: Configure Jenkins and monitoring host (dev environment)
  hosts: jenkins_host
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - common
    - docker
    - jenkins
    - node_exporter
    - monitoring
    - grafana
